spring.application.name=backend
server.port=8081
spring.data.mongodb.uri=mongodb+srv://pawarinv:messimyoh@cluster0.bb5x9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=backend
